--------------------------------------------------------
--  Fichier cr�� - samedi-juillet-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADRESSE
--------------------------------------------------------

  CREATE TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" 
   (	"ADDID" VARCHAR2(7 BYTE), 
	"STREET" VARCHAR2(75 BYTE), 
	"CITY" VARCHAR2(35 BYTE) DEFAULT ('MONTREAL'), 
	"STATE" VARCHAR2(2 BYTE) DEFAULT ('QC'), 
	"CODE" VARCHAR2(7 BYTE), 
	"COUNTRY" VARCHAR2(25 BYTE) DEFAULT ('CANADA')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PROJET_FINAL_GROUPE3.ADRESSE
SET DEFINE OFF;
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('TS0001','15, Fleury Street','Montreal','QC','H2C 1S7','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('RK0002','19510, 102 Ave','Edmonton','AB','T5S 1K2','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AG0003','50, Hey Ave','Burnaby',null,'V5G 3H7','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('FH0004','437, rue Boyer','Montreal','QC','H2J 3E6','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('KD0005','53, Adanac','Qu�bec','QC','G1C 7B7','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AB0006','240, rue des Nations','Saint-Laurent','QC','H4R 3G4','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AS0007','55, Carey Ave','Burnaby','BC','V5G 3H2','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('GB0008','35, Ellice Ave','Winnipeg','MB','R3B 1C6','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AEY009','2823, Westmorland St','Fredericton','NB','E3B 3L8','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AD0010','984, Morning Street','Saskatoon ',null,'S7K 3R9','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JJS011','22, Brownlow Ave ','Dartmouth','NS','B3B 1T5','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AR0012','240 Simcoe St N','Oshawa','ON','L1G 0C5','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('CB1013','39112, Empire Ave ','St. John''s','NL','A1E 1W6','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('TS0014','2 Rue des Villes','Qu�bec','SK','S6V 7S4','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('ET0015','1936 Great George St ','Charlottetown','PE','C1A 4K7','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('FH0016','1, Greater Boul','Montreal',null,'H1L 4I4','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JL0017','1130 Idylwyld Dr N','Saskatoon ','SK','S7K 3R5','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JD888','555 Boul St-Laurent #2000','Montreal','QC','H2T 1S6','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JP999','201, 99 Ave','Edmonton','AB','T3X 1K3','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('LA444','33, National Street','Qu�bec','QC','G2A 2D8','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('AG222','4003, rue Jean Boyer','Montreal','QC','H1X 3F2','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('PC111','53, Amical Street','Qu�bec','QC','G2D 3F7','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('BJ333','2, Nation Ville','Saint-Laurent','QC','H4R 3G4','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('MS555','555, Danley Ave','Burnaby','BC','V5G 3H2','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('JP777','3995, Space Ave','Winnipeg','MB','R3B 1C6','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP000','437, rue Boyer','Montreal','QC','H2J 3E6','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP001','43, Sherbrooke St','Montreal','QC','H1L 4I4','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP002','55, Carey Ave','Burnaby','BC','V5G 3H2','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP003','22, Brownlow Ave ','Dartmouth','NS','B3B 1T5','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP004','1130 Idylwyld Dr N','Saskatoon ','SK','S7K 3R5','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP005','15, Fleury Street','Montreal','QC','H2C 1S7','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP006','437, rue Boyer','Montreal','QC','H2J 3E6','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP007','2823, Westmorland St','Fredericton','NB','E3B 3L8','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP008','240 Simcoe St N','Oshawa','ON','L1G 0C5','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP009','55, Carey Ave','Burnaby','BC','V5G 3H2','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP010','55, Carey Ave','Burnaby','BC','V5G 3H2','CANADA');
Insert into C##PROJET_FINAL_GROUPE3.ADRESSE (ADDID,STREET,CITY,STATE,CODE,COUNTRY) values ('SHIP011','1130 Idylwyld Dr N','Saskatoon ','SK','S7K 3R5','CANADA');
--------------------------------------------------------
--  DDL for Index ADDID_ADRESSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJET_FINAL_GROUPE3"."ADDID_ADRESSE_PK" ON "C##PROJET_FINAL_GROUPE3"."ADRESSE" ("ADDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADRESSE
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" MODIFY ("STREET" CONSTRAINT "STREET_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" MODIFY ("CITY" CONSTRAINT "CITY_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" MODIFY ("CODE" CONSTRAINT "CODE_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" MODIFY ("COUNTRY" CONSTRAINT "COUNTRY_ADRESSE_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" ADD CONSTRAINT "STATE_ADRESSE_CHK" CHECK (STATE IN('AB', 'BC', 'MB', 'NB', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'NL', 'NT', 'YT')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" ADD CONSTRAINT "COUNTRY_ADRESSE_CHK" CHECK (COUNTRY IN('CANADA')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."ADRESSE" ADD CONSTRAINT "ADDID_ADRESSE_PK" PRIMARY KEY ("ADDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


--------------------------------------------------------
--  Fichier cr�� - samedi-juillet-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "C##PROJET_FINAL_GROUPE3"."CLIENTS" 
   (	"CID" VARCHAR2(6 BYTE), 
	"FNAME" VARCHAR2(30 BYTE), 
	"LNAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CLIADD" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PROJET_FINAL_GROUPE3.CLIENTS
SET DEFINE OFF;
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3001','Tendulkar','Sachin',null,'tsach@videotron.ca','TS0001');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3002','Rahul','Kapur','587-777-3315','kapurR@yahoo.ca','RK0002');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3003','Ajay','Gandhi','438-456-9870','ag@mail.com','AG0003');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3004','Fifi','Hill','514-789-4561','fifih@hotmail.com','FH0004');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3005','Kapil','Dev','418-251-4587','kapild@gmail.com','KD0005');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3006','Anil','Brousseau','819-564-2150','ab@wanadoo.com','AB0006');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3007','Anabelle','Dessalines','604-683-6159','adessa@gmail.com','AS0007');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3008','Georges','Bosse',null,'georgesb@yahoo.com','GB0008');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3009','Arnold','Marley',null,'amarley@mail.com','AEY009');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3010','Andrew','Dube','905-351-8668','adube@hotmail.com','AD0010');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3011','Jean-Jacques','Saunier','902-835-3727','jjs@mail.com','JJS011');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3012','Anne','Reis',null,'anner@gmail.com','AR0012');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3013','Claude','Bertrand','877-696-3737','claudeb@gmail.com','CB1013');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3014','Tendulkar','Sachin',null,'sachint@mail.com','TS0014');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3015','Emilie','Tremblay','902-367-3447','emiliet@gmail.com','ET0015');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3016','Fifi','Hill',null,'fifih@yahoo.com','FH0016');
Insert into C##PROJET_FINAL_GROUPE3.CLIENTS (CID,FNAME,LNAME,PHONE,EMAIL,CLIADD) values ('CL3017','Julien','Larouche','866-467-4278','julienL@caramail.com','JL0017');
--------------------------------------------------------
--  DDL for Index CID_CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJET_FINAL_GROUPE3"."CID_CLIENTS_PK" ON "C##PROJET_FINAL_GROUPE3"."CLIENTS" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."CLIENTS" MODIFY ("FNAME" CONSTRAINT "FNAME_CLIENTS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."CLIENTS" MODIFY ("LNAME" CONSTRAINT "LNAME_CLIENTS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."CLIENTS" ADD CONSTRAINT "PHONE_CLIENTS_CHK" CHECK (REGEXP_LIKE (PHONE,'^[2-9]+[0-9]+[0-9]+[-]+[2-9]+[0-9]+[0-9]+[-]+[0-9]{4}')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."CLIENTS" ADD CONSTRAINT "EMAIL_CLIENTS_CHK" CHECK (REGEXP_LIKE (EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."CLIENTS" ADD CONSTRAINT "CID_CLIENTS_PK" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."CLIENTS" ADD CONSTRAINT "CLIADD_CLIENTS_FK" FOREIGN KEY ("CLIADD")
	  REFERENCES "C##PROJET_FINAL_GROUPE3"."ADRESSE" ("ADDID") ENABLE;



--------------------------------------------------------
--  Fichier cr�� - samedi-juillet-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" 
   (	"SID" NUMBER(8,0), 
	"FNAME" VARCHAR2(30 BYTE), 
	"LNAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"SUPADD" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PROJET_FINAL_GROUPE3.FOURNISSEURS
SET DEFINE OFF;
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('200','John','Dave','514-999-4500','jod@ubisoft.ca','JD888');
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('201','Josiane','Paul','587-301-3395','josia@nintendo.com','JP999');
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('202','Lucien','Allard','438-555-9520','la@stargam.com','LA444');
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('203','Amelie','Grignard','514-201-4551','amelieg@electro.com','AG222');
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('204','Peppa','Couillard','418-308-4597','pepcouil@sony.com','PC111');
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('205','Benson','Jack','819-999-2990','bjack@sega.com','BJ333');
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('206','Manpreet','Shah','604-666-6666','mshah@nsoft.com','MS555');
Insert into C##PROJET_FINAL_GROUPE3.FOURNISSEURS (SID,FNAME,LNAME,PHONE,EMAIL,SUPADD) values ('207','Jewish','Patel','204-225-0023','jpatel@misoft.com','JP777');
--------------------------------------------------------
--  DDL for Index SID_FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJET_FINAL_GROUPE3"."SID_FOURNISSEURS_PK" ON "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" MODIFY ("FNAME" CONSTRAINT "FNAME_FOURNISSEURS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" MODIFY ("LNAME" CONSTRAINT "LNAME_FOURNISSEURS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" ADD CONSTRAINT "PHONE_FOURNISSEURS_CHK" CHECK (REGEXP_LIKE (PHONE,'^[2-9]+[0-9]+[0-9]+[-]+[2-9]+[0-9]+[0-9]+[-]+[0-9]{4}')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" ADD CONSTRAINT "EMAIL_FOURNISSEURS_CHK" CHECK (REGEXP_LIKE (EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" ADD CONSTRAINT "SID_FOURNISSEURS_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" ADD CONSTRAINT "SUPADD_FOURNISSEURS_FK" FOREIGN KEY ("SUPADD")
	  REFERENCES "C##PROJET_FINAL_GROUPE3"."ADRESSE" ("ADDID") ENABLE;



--------------------------------------------------------
--  Fichier cr�� - samedi-juillet-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JEUXVIDEOS
--------------------------------------------------------

  CREATE TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" 
   (	"VGID" NUMBER(8,0), 
	"TITLE" VARCHAR2(70 BYTE), 
	"AUTHORS" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(600 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"PUBLIDATE" DATE, 
	"PURCHPRICE" NUMBER(8,0), 
	"CATALPRICE" NUMBER(10,0), 
	"STOCKNUMBER" NUMBER(6,0), 
	"SID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PROJET_FINAL_GROUPE3.JEUXVIDEOS
SET DEFINE OFF;
Insert into C##PROJET_FINAL_GROUPE3.JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values ('9999995','Animal Crossing: New Horizons','Nintendo','Animal Crossing: New Horizons is a life simulation video game developed and published by Nintendo. The fifth main series title in the Animal Crossing series, New Horizons was released on the Nintendo Switch on March 20, 2020. ','SIMULATION',to_date('20/03/20','DD/MM/RR'),'50','60','10',null);
Insert into C##PROJET_FINAL_GROUPE3.JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values ('9999994','Murder by Numbers','Mediatonic','Murder by Numbers is a video game developed by Mediatonic and published by The Irregular Corporation. It was released on March 5, 2020 for Nintendo Switch and Microsoft Windows. The game is a hybrid of visual novels with nonogram-style logic puzzles to progress the story. ','PUZZLE',to_date('21/03/20','DD/MM/RR'),'55','63','8',null);
Insert into C##PROJET_FINAL_GROUPE3.JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values ('9999993','Pok�mon Mystery Dungeon: Rescue Team DX','Spike Chunsoft','Pok�mon Mystery Dungeon: Rescue Team DX is a 2020 remake of the 2005 video games Pok�mon Mystery Dungeon: Blue Rescue Team and Red Rescue Team. It is part of the Pok�mon Mystery Dungeon series developed by Spike Chunsoft, published by The Pok�mon Company and distributed by Nintendo for the Nintendo Switch.','ROLE-PLAYING',to_date('22/03/20','DD/MM/RR'),'60','75','4',null);
Insert into C##PROJET_FINAL_GROUPE3.JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values ('9999992','Taur ','Echo Entertainment','Taur is an action-strategy sci-fi game developed and published by Echo Entertainment, released on 20 February 2020.The game is inspired by the tower defense genre and mixes strategy with wave survival.','ACTION',to_date('23/03/20','DD/MM/RR'),'60','76','8',null);
Insert into C##PROJET_FINAL_GROUPE3.JEUXVIDEOS (VGID,TITLE,AUTHORS,DESCRIPTION,CATEGORY,PUBLIDATE,PURCHPRICE,CATALPRICE,STOCKNUMBER,SID) values ('9999991','FIFA 20','EA Vancouver','FIFA 20 is a football simulation video game published by Electronic Arts as part of the FIFA series. It is the 27th installment in the FIFA series, and was released on 27 September 2019 for Microsoft Windows, PlayStation 4, Xbox One, and Nintendo Switch.','SPORTS',to_date('24/03/20','DD/MM/RR'),'80','103','12',null);
--------------------------------------------------------
--  DDL for Index VGID_JEUXVIDEOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJET_FINAL_GROUPE3"."VGID_JEUXVIDEOS_PK" ON "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ("VGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JEUXVIDEOS
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" MODIFY ("TITLE" CONSTRAINT "TITLE_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" MODIFY ("AUTHORS" CONSTRAINT "AUTHORS_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" MODIFY ("CATEGORY" CONSTRAINT "CATEGORY_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" MODIFY ("PUBLIDATE" CONSTRAINT "PUBLIDATE_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" MODIFY ("PURCHPRICE" CONSTRAINT "PURCHPRICE_JEUXVIDEOS_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ADD CONSTRAINT "CATEGORY_JEUXVIDEOS_CHK" CHECK (CATEGORY IN('ACTION','ACTION-ADVENTURE','ADVENTURE','ROLE-PLAYING','SIMULATION','STRATEGY','SPORTS','PUZZLE','IDLE','OTHER')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ADD CONSTRAINT "PUBLIDATE_JEUXVIDEOS_CHK" CHECK (PUBLIDATE>TO_DATE('2015-12-31','yyyy-mm-dd')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ADD CONSTRAINT "PURCHPRICE_JEUXVIDEOS_CHK" CHECK (PURCHPRICE>0) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ADD CONSTRAINT "CATALPRICE_JEUXVIDEOS_CHK" CHECK (CATALPRICE>0) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ADD CONSTRAINT "STOCKNUMBER_JEUXVIDEOS_CHK" CHECK (STOCKNUMBER>0) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ADD CONSTRAINT "VGID_JEUXVIDEOS_PK" PRIMARY KEY ("VGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEUXVIDEOS
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ADD CONSTRAINT "SID_JEUXVIDEOS_FK" FOREIGN KEY ("SID")
	  REFERENCES "C##PROJET_FINAL_GROUPE3"."FOURNISSEURS" ("SID") ENABLE;




--------------------------------------------------------
--  Fichier cr�� - samedi-juillet-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" 
   (	"OID" VARCHAR2(6 BYTE), 
	"PLACDATE" DATE DEFAULT SYSDATE, 
	"PAYTYPE" VARCHAR2(25 BYTE), 
	"SHIPADD" VARCHAR2(7 BYTE), 
	"CID" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PROJET_FINAL_GROUPE3.COMMANDES
SET DEFINE OFF;
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0010',to_date('20/03/20','DD/MM/RR'),'MASTERCARD','SHIP000','CL3004');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0011',to_date('20/03/20','DD/MM/RR'),'MASTERCARD','SHIP001','CL3016');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0012',to_date('21/03/20','DD/MM/RR'),'VISA','SHIP002','CL3007');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0013',to_date('21/03/20','DD/MM/RR'),'PAYPAL','SHIP003','CL3011');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0014',to_date('22/03/20','DD/MM/RR'),'BANK TRANSFER','SHIP004','CL3017');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0015',to_date('01/02/20','DD/MM/RR'),'VISA','SHIP005','CL3001');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0016',to_date('18/02/20','DD/MM/RR'),'MASTERCARD','SHIP006','CL3004');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0017',to_date('01/03/20','DD/MM/RR'),'PAYPAL','SHIP007','CL3009');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0018',to_date('25/02/20','DD/MM/RR'),'VISA','SHIP008','CL3012');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0019',to_date('15/01/20','DD/MM/RR'),'PAYPAL','SHIP009','CL3007');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0020',to_date('21/03/20','DD/MM/RR'),'MASTERCARD','SHIP010','CL3007');
Insert into C##PROJET_FINAL_GROUPE3.COMMANDES (OID,PLACDATE,PAYTYPE,SHIPADD,CID) values ('OD0021',to_date('21/03/19','DD/MM/RR'),'VISA','SHIP011','CL3017');
--------------------------------------------------------
--  DDL for Index OID_COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJET_FINAL_GROUPE3"."OID_COMMANDES_PK" ON "C##PROJET_FINAL_GROUPE3"."COMMANDES" ("OID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" MODIFY ("PLACDATE" CONSTRAINT "PLACDATE_COMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" MODIFY ("PAYTYPE" CONSTRAINT "PAYTYPE_COMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" MODIFY ("SHIPADD" CONSTRAINT "SHIPADD_COMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" ADD CONSTRAINT "PAYTYPE_COMMANDES_CHK" CHECK (PAYTYPE IN('MASTERCARD','VISA','PAYPAL','BANK TRANSFER')) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" ADD CONSTRAINT "OID_COMMANDES_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" ADD CONSTRAINT "SHIPADD_COMMANDES_FK" FOREIGN KEY ("SHIPADD")
	  REFERENCES "C##PROJET_FINAL_GROUPE3"."ADRESSE" ("ADDID") ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."COMMANDES" ADD CONSTRAINT "CID_COMMANDES_FK" FOREIGN KEY ("CID")
	  REFERENCES "C##PROJET_FINAL_GROUPE3"."CLIENTS" ("CID") ENABLE;




--------------------------------------------------------
--  Fichier cr�� - samedi-juillet-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DETAILSCOMMANDES
--------------------------------------------------------

  CREATE TABLE "C##PROJET_FINAL_GROUPE3"."DETAILSCOMMANDES" 
   (	"QUANTITY" NUMBER(10,0) DEFAULT 1, 
	"QCTAXRATE" NUMBER(6,0) DEFAULT 0.09975, 
	"CANTAXRATE" NUMBER(6,0) DEFAULT 0.05, 
	"SALPRICE" NUMBER(10,0), 
	"OID" VARCHAR2(6 BYTE), 
	"VGID" NUMBER(8,0), 
	"TOTAL" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES
SET DEFINE OFF;
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('5','0','0','60','OD0010',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('4','0','0','60','OD0010',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('2','0','0','63','OD0011',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('1','0','0','75','OD0012',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('5','0','0','103','OD0013',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('6','0','0','76','OD0014',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('2','0','0','63','OD0015',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('1','0','0','60','OD0016',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('1','0','0','63','OD0017',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('2','0','0','103','OD0018',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('3','0','0','103','OD0010',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('1','0','0','75','OD0019',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('1','0','0','103','OD0020',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('1','0','0','60','OD0021',null,null);
Insert into C##PROJET_FINAL_GROUPE3.DETAILSCOMMANDES (QUANTITY,QCTAXRATE,CANTAXRATE,SALPRICE,OID,VGID,TOTAL) values ('1','0','0','103','OD0014',null,null);
--------------------------------------------------------
--  Constraints for Table DETAILSCOMMANDES
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."DETAILSCOMMANDES" MODIFY ("QUANTITY" CONSTRAINT "QUANTITY_DETAILSCOMMANDES_NN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."DETAILSCOMMANDES" ADD CONSTRAINT "QUANTITY_DETAILSCOMMANDES_CHK" CHECK (QUANTITY>0) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."DETAILSCOMMANDES" ADD CONSTRAINT "QCTAXRATE_DETAILSCOMMANDES_CHK" CHECK (QCTAXRATE IN(0,0.09975)) ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."DETAILSCOMMANDES" ADD CONSTRAINT "CANTAXRATE_DETAILSCOMMANDES_CHK" CHECK (CANTAXRATE IN(0,0.05)) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETAILSCOMMANDES
--------------------------------------------------------

  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."DETAILSCOMMANDES" ADD CONSTRAINT "OID_DETAILSCOMMANDES_FK" FOREIGN KEY ("OID")
	  REFERENCES "C##PROJET_FINAL_GROUPE3"."COMMANDES" ("OID") ENABLE;
  ALTER TABLE "C##PROJET_FINAL_GROUPE3"."DETAILSCOMMANDES" ADD CONSTRAINT "VGID_DETAILSCOMMANDES_FK" FOREIGN KEY ("VGID")
	  REFERENCES "C##PROJET_FINAL_GROUPE3"."JEUXVIDEOS" ("VGID") ENABLE;
